# Commands that tell the app to stop accepting input and switch to the next phase
# Default: "-r", "--run"
stop commands:
  - "-r"
  - "--run"

# Should the cost calculator get items the player already has?
# Default: true
use already has items: true

#Current pack to use
# Default: "packs/default.yaml"
current pack: "packs/default.yaml"
