# Commands that tell the app to stop accepting input and switch to the next phase
# Default: "-r", "--run"
stop commands:
  - "-r"
  - "--run"

# Should the cost calculator get items the player already has?
# Default: false
use already has items: false

# Current pack to use
# Default: "packs/default.yaml"
current pack: packs/po2k.yaml

# Addons to use (will be loaded along with the current pack)
addons: [
]

# Skip asking for sub-resources the player already has?
# Default: true
skip resources: true

# Print items in calchelper that don't have recipes
# Default: true
print items without recipes: true

# Display all raw materials after using calchelper and/or using check
# Default: true
display all raw materials: true

# Produce HTML output
# Default: false
html output: true