# Should the cost calculator get items the user already has?
# Default: false
use preexisting items: false

# Current pack to use
# Default: "packs/example.yaml"
current pack: packs/example.yaml

# Addons to use (will be loaded along with the current pack)
addons: [
]

# Skip asking for sub-resources the user already has?
# Default: true
skip resources: true

# Print items in calchelper that don't have recipes
# Default: true
print items without recipes: true

# Display all raw materials after using calchelper and/or using check
# Default: true
display all raw materials: true

# Produce HTML output
# Default: false
html output: false

# Show how much is left over for each craft (for subcrafts)
# Default: false
show left over amount: false

# Use the alternate method for sorting depths for display based on the item used to craft it with the highest sorting depth
# Default: false
use alternate sorting depth method: false

# Show AE2's crafting bytes calculation at the end of the page
# Default: false
show crafting bytes: false